

# Specify the compiler options or flags, linking libraries
# and any debugging information flags as a variables
CC = gcc
LIBS = -lm

#
# Specify the target
all: lab1


# Specify how the executables should be created from source files
lab1: lab1.c
	$(CC) lab1.c -o lab1 $(LIBS)

# Specify the object files and executables that are generated
# and need to be removed to re-compile the whole thing
clean:
	rm -f lab1




