
# Specify the compiler options or flags, linking libraries
# and any debugging information flags as a variables
CC = gcc

#
# Specify the target
all: lab4


# Specify how the executables should be created from source files
lab4: lab4.c lab4.h
	$(CC) lab4.c -o lab4

# Specify the object files and executables that are generated
# and need to be removed to re-compile the whole thing
clean:
	rm -f lab4


