

# Specify the compiler options or flags, linking libraries
# and any debugging information flags as a variables
CC = gcc

#
# Specify the target
all: lab2


# Specify how the executables should be created from source files
lab2: lab2.c
	$(CC) lab2.c -o lab2

# Specify the object files and executables that are generated
# and need to be removed to re-compile the whole thing
clean:
	rm -f lab2




