
# Specify the compiler options or flags, linking libraries
# and any debugging information flags as a variables
CC = gcc

#
# Specify the target
all: lab3


# Specify how the executables should be created from source files
lab3: lab3.c lab3.h
	$(CC) lab3.c -o lab3

# Specify the object files and executables that are generated
# and need to be removed to re-compile the whole thing
clean:
	rm -f lab3


