

# Specify the compiler options or flags, linking libraries
# and any debugging information flags as a variables
CC = gcc

#
# Specify the target
all: BST


# Specify how the executables should be created from source files
BST: BST.c
	$(CC) BST.c BST.h -o BST

# Specify the object files and executables that are generated
# and need to be removed to re-compile the whole thing
clean:
	rm -f BST




